sudo: required
#we use java
language: java

#we add the java development kit (jdk)
jdk:
- openjdk8

services:
#Linking Travis CI and Docker
- docker

before_install:
- mvn clean

install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- export TAG=latest
- export IMAGE_NAME=amasrikanth/springboot-cicd
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:${TRAVIS_COMMIT::7} $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME